### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by andress134** [lilmond/sudos#2]
Hello sir @lilmond 
Can make this script to detect all pages of target and spam all with requests? also attacking using combi proxy using http +socks4/5 in same time, send data using  random get, post, head in same time, improving the tls to bypass cf header?
using custom header to bypass cf page,  a function to get cookies from header, to bypass cloudflare
Also, what about using a lib based chromedriver, https://github.com/ultrafunkamsterdam/undetected-chromedriver just to get cookies, and bypass the cdn page ? or using this lib https://github.com/MatheusVp2/hCaptcha-Solver-MR can bypass cf uam +  hcaptcha

// for bypass any waf can be used also app.scrapingant.com api, this can get cookies and bypass alot waf pages

The final question

it is possible to implement a library
So, does the cc.py script call a library to get the real IP address of a target, and then send requests to that ip?
created a function to call to this library and get real ip
1. start cc.py select method  ''bypass-ip''
2. put target : https://cf-target.com
3. sleep 60 sec (looking for real ip, if detect it)
4. replace https://cf-target.com with real ip  http://ip/
5. start sending requests ??
https://github.com/MrH0wl/Cloudmare  that lib can found real ip of alot websites

sorry for bad my english
I hope you understand what I mean. Respect.

**Comment by lilmond** [comment]
Hi, @andress134! I hope you're having a nice day.

Thanks for your suggestions! I found this to be really helpful and I really appreciate it. I will definitely use these ideas and implement it to this project soon!

**Comment by andress134** [comment]
> Hi, @andress134! I hope you're having a nice day.
> 
> Thanks for your suggestions! I found this to be really helpful and I really appreciate it. I will definitely use these ideas and implement it to this project soon!

take a look here sir https://github.com/SocketDisconnect/AntiFlare

```python
import requests

data = {
'method':'session',
'url':'https://target-url',
'timeout':'20'
}

r = requests.post('http://127.0.0.1:3000/request',json=data)
print(r.text)
print(r.headers)```

**Comment by andress134** [comment]
@lilmond whenu will release a new update sir?
the tool look not working, tested on debian 9
do not send any reuqests on any dstat

**Comment by lilmond** [comment]
> @lilmond whenu will release a new update sir?

Hey, I'm finding out a way to generate Cloudflare sessions without receiving and executing JavaScript codes in Python because somehow, receiving data will make the tool much slower.

Thanks!

**Comment by andress134** [comment]
> > @lilmond whenu will release a new update sir?
> 
> Hey, I'm finding out a way to generate Cloudflare sessions without receiving and executing JavaScript codes in Python because somehow, receiving data will make the tool much slower.
> 
> Thanks!

any new update for  uam sir?

**Comment by Egida** [comment]
upd

**Comment by lilmond** [comment]
> any new update for uam sir?

Hey! Sorry for late update. Cloudflare modifies their anti-bot protection page occasionally, so we have been having trouble and arguments choosing a good library to implement in this tool lately but we've chosen one and will implement in this tool on the next updates. Thank you so much!
