### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by andress134** [lilmond/sudos#4]
Hello man @lilmond , tested on some random websites, the tool look doest working

python3.8 sudos.py -z socks5 -x socks.txt -t 500 -v 0 https://manelemp3.net/ 

just show me 

T: 500    C: 0      H: 0         U: 0.00 B         D: 0.00 B
T: 500    C: 0      H: 0         U: 0.00 B         D: 0.00 B
T: 500    C: 0      H: 0         U: 0.00 B         D: 0.00 B

**Comment by lilmond** [comment]
Hey! Thanks for letting us know about this! We found what's causing this error which is `SSLV3_ALERT_HANDSHAKE_FAILURE` and trying to figure out how to fix this issue. Again, thanks and we really appreciate it! Wishing you a nice day!

**Comment by andress134** [comment]
> Hey! Thanks for letting us know about this! We found what's causing this error which is `SSLV3_ALERT_HANDSHAKE_FAILURE` and trying to figure out how to fix this issue. Again, thanks and we really appreciate it! Wishing you a nice day!

When will release a new update sir

**Comment by lilmond** [comment]
> When will release a new update sir

Hey! We have fixed the issue. Thanks for waiting!
