### ISSUE TITLE
Sugestion #2

### ISSUE THREAD

**Issue by andress134** [lilmond/sudos#5]
Hello sir @lilmond  have you found a way to bypass cloudflare?
Could you do something to detect the firewall automatically?
For example, to check the header and if it detects cloudflare in the header, to return the status code, etc.
and callback to selenium to bypass and get cookies?
If header return ddos-guard, enable the limit function so that it does not require captcha resolution
Also include proxy scraper to auto download proxies or get it directly from url to update automatic
Using any library to get default cookie from any target and validate browser to generate like fake browser to bypass

Sry my english is not so good

**Comment by Awei2020** [comment]
can you help me

**Comment by andress134** [comment]
hey sir @lilmond  what about cookie scraper function? alot target will validate the requests just if u provide the cookie

**Comment by andress134** [comment]
@lilmond  alot of websites starting to block http/1.1 you can update it using a function that support all http1.0 1.1 2.0 etc

**Comment by andress134** [comment]
@lilmond  any new updates soon?

**Comment by lilmond** [comment]
Hey @andress134! We apologize we couldn't really implement a cookie scraper at the moment to keep the stability of the program. If you have more suggestions, please don't hesistate to tell us about it! We wish you a nice day!
