### ISSUE TITLE
I want to know how to deal this

### ISSUE THREAD

**Issue by Awei2020** [lilmond/sudos#6]
python3.9 sudos.py https://baidu
Traceback (most recent call last):
  File "/root/sudos/sudos.py", line 485, in <module>
    main()
  File "/root/sudos/sudos.py", line 480, in main
    curses.wrapper(c_main)
  File "/python/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/root/sudos/sudos.py", line 418, in c_main
    curses.init_pair(1, 196, -1)
_curses.error: init_pair() returned ERR

**Comment by lilmond** [comment]
Hey! Thanks for reporting this issue. Can we know which Operating System are you running with this tool? Thanks!

**Comment by Awei2020** [comment]
centos7
did you have telegram number?
i want to study with you

**Comment by lilmond** [comment]
Regarding the issue, we may have fixed it now. However, if you're still having issue running the program. You may execute this command in your Terminal: `export TERM='xterm-256color'` and re-run the program.

> did you have telegram number?

Apparently, we only use Discord for communications.

Have a good one!
