### ISSUE TITLE
Err

### ISSUE THREAD

**Issue by Egida** [lilmond/sudos#8]
[+] Downloading proxies.txt Exception in thread Thread-2: Traceback (most recent call last): File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner self.run() File "/usr/lib/python3.8/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "sudos.py", line 86, in fetch_proxy with open(logfile, "a") as file: FileNotFoundError: [Errno 2] No such file or directory: './etc/proxies.txt'

**Comment by lilmond** [comment]
Good day! We may have fixed what's causing this issue. If you're still having the same problem, please don't hesitate to reply for furthermore assistance.
