### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Timezero1** [lilmond/sudos#9]
I don’t understand how to add my proxies, it was possible to make just an example of all ready-made commands in the description, this will remove a lot of unnecessary questions

**Comment by lilmond** [comment]
Good day, sir/ma'am!

We appreciate your feedback and we made a little documentation on how to use your own proxy list (link below). We hope it helps! Again, thanks for your feedback and have a good one!

https://github.com/lilmond/sudos/blob/main/docs/custom_proxy.md#custom-proxy-list

**Comment by Timezero1** [comment]
Thanks a lot! uam cloudflare can be bypassed?

**Comment by lilmond** [comment]
Glad if that helps. Apparently, we haven't implemented any sort of bypassing tool for stability reason and to keep it capable of running on any platform.

Moreover, please don't hesitate to submit more feedback. We would love to hear more from you! Have a nice one!
